### ISSUE TITLE
PINCache doesn't build in Xcode 12 Beta 4

### ISSUE THREAD

**Issue by mycroftcanner** [pinterest/PINCache#275]
It generates a lot of semantic issues:

> Incompatible block pointer types sending 'PINMemoryCacheObjectBlock  _Nullable __strong' (aka 'void (^__strong)(PINMemoryCache * _Nonnull __strong, NSString * _Nonnull __strong, id  _Nullable __strong)') to parameter of type 'PINCacheObjectBlock _Nonnull' (aka 'void (^)(id<PINCaching>  _Nonnull __strong, NSString * _Nonnull __strong, id  _Nullable __strong)')

**Comment by richieWave** [comment]
This

**Comment by mycroftcanner** [comment]
It builds now after this [commit](https://github.com/pinterest/PINCache/pull/273/files/3267654d1d24fdb22bfb61aaa62b2d2e511554f0) but tests fail.

PINMemoryCache is also broken

**Comment by garrettmoon** [comment]
@mycroftcanner Tests succeed for me locally, can you explain which tests fail and what you mean by PINMemoryCache is broken?

**Comment by arangato** [comment]
I had a bunch of compilation errors in tests as well. All looking like the one @mycroftcanner initially reported. I've fixed it in [this PR](https://github.com/pinterest/PINCache/pull/276).

**Comment by garrettmoon** [comment]
@mycroftcanner I just merged @arangato 's PR (thank you!), does this address what you were hitting?

**Comment by Anatol1986** [comment]
The same issues also available on Xcode Version 12.0 beta 5

**Comment by mycroftcanner** [comment]
@garrettmoon CocoaPods still look for old version and you specify the master branch then PINRemoteImage is out of sync and Texture won't build too.

**Comment by bluemachine** [comment]
Issue still persists in Xcode 12 beta 5 with following pods
PINCache (3.0.1-beta.8)
PINOperation (1.1.2)
PINRemoteImage (3.0.0)

![Screenshot 2020-08-28 at 23 49 25](https://user-images.githubusercontent.com/880597/91617820-27751f80-e989-11ea-9440-ebed8e5d839d.png)

**Comment by bluemachine** [comment]
Upgraded to Xcode 12 beta 6 and getting just this 1 issue. Hoping you could fix it soon. 

![Screenshot 2020-08-29 at 16 25 24](https://user-images.githubusercontent.com/880597/91639088-58e6fd00-ea14-11ea-8d38-e669cf1ece5c.png)

**Comment by ehsan-ff** [comment]
> Upgraded to Xcode 12 beta 6 and getting just this 1 issue. Hoping you could fix it soon.
> 
> ![Screenshot 2020-08-29 at 16 25 24](https://user-images.githubusercontent.com/880597/91639088-58e6fd00-ea14-11ea-8d38-e669cf1ece5c.png)

Facing the same issue on Xcode 12 beta 6.

**Comment by hexadecimal-REBOOT** [comment]
Has anyone been successful with getting it to build. I'm getting the same error message Incompatible block pointer types.

**Comment by sagesse-cn** [comment]
add the flags into bulid config CFLAGS to disable check
```
-Xclang -fcompatibility-qualified-id-block-type-checking
``

**Comment by garrettmoon** [comment]
This has been fixed in PINCache 3.0.1. We'll put out a new PINRemoteImage release which includes this soon.

**Comment by bluemachine** [comment]
When we install the pod PINRemoteImage - it installs with following pods

Installing PINCache (3.0.1-beta.8)
Installing PINOperation (1.1.2)
Installing PINRemoteImage (3.0.0)

To update as suggested - when we install PINCache it updates to latest version but installs an older version of PINRemoteImage and followings pods.

Installing FLAnimatedImage (1.0.12)
Installing PINCache 3.0.1 (was 3.0.1-beta.8)
Installing PINOperation 1.2 (was 1.1.2)
Installing PINRemoteImage 2.1.4 (was 3.0.0)

This gives 4 build errors - screenshots below
![Screenshot 2020-09-08 at 20 50 41](https://user-images.githubusercontent.com/880597/92516205-26f44880-f215-11ea-9352-4bf24d3486ec.png)
![Screenshot 2020-09-08 at 20 50 52](https://user-images.githubusercontent.com/880597/92516214-2956a280-f215-11ea-9bae-8685b3e26d87.png)
![Screenshot 2020-09-08 at 20 51 00](https://user-images.githubusercontent.com/880597/92516217-2a87cf80-f215-11ea-81dd-88d61f6c5916.png)
![Screenshot 2020-09-08 at 20 51 10](https://user-images.githubusercontent.com/880597/92516221-2b206600-f215-11ea-8704-c95721890494.png)

Hope this helps in recreating the issue.

**Comment by alisamaiee** [comment]
I have fixed it doing these steps:

1- Find PINCache+PINRemoteImageCaching.m file in your project and replace it with this file:
https://github.com/pinterest/PINRemoteImage/blob/master/Source/Classes/PINCache/PINCache%2BPINRemoteImageCaching.m

2- Apply changes of this commit to your project files (or you can simply replace the files witch had change during this commit):
https://github.com/pinterest/PINCache/commit/10b3c3c6ea75607455d652413ed53eb9cbc88e98

Done!

**Comment by Rexrohan** [comment]
> a temporary solution add the flags into bulid config `CFLAGS` to disable check
> 
> ```
> -Xclang -fcompatibility-qualified-id-block-type-checking
> ```

Is this works

**Comment by Rexrohan** [comment]
> a temporary solution add the flags into bulid config `CFLAGS` to disable check
> 
> ```
> -Xclang -fcompatibility-qualified-id-block-type-checking
> ```

where to add the flag, I have added in build settings flags still error shows.

**Comment by Rexrohan** [comment]
> I have fixed it doing these steps:
> 
> 1- Find PINCache+PINRemoteImageCaching.m file in your project and replace it with this file:
> https://github.com/pinterest/PINRemoteImage/blob/master/Source/Classes/PINCache/PINCache%2BPINRemoteImageCaching.m
> 
> 2- Apply changes of this commit to your project files (or you can simply replace the files which had change during this commit):
> [10b3c3c](https://github.com/pinterest/PINCache/commit/10b3c3c6ea75607455d652413ed53eb9cbc88e98)
> 
> Done!

this one also not working for me

**Comment by SAYEDALISINA93** [comment]
Still have this issue with the Xcode 12 final version.

Should I change my Xcode back to 11 or there is a solution to solve it?

**Comment by VictorZhang2014** [comment]
![image](https://user-images.githubusercontent.com/6853884/96837343-d9583600-1478-11eb-9940-ee872a5f1499.png)
![image](https://user-images.githubusercontent.com/6853884/96837372-e83ee880-1478-11eb-85e9-f676f9104471.png)

It's not working on Xcode 12.0, as you all mentioned above.

**Comment by sagesse-cn** [comment]
> It's not working on Xcode 12.0, as you all mentioned above.

You must use `PINCache` version 3.0.2 or above.

**Comment by timeview** [comment]
I did try PINCache 3.0.3 but still get same errors - Any upset on this issue ?

**Comment by bolee** [comment]
upgrade the latest version 3.0.3.
